### ISSUE TITLE
SSH’ing to Unifi equipment with Fedora 37 

### ISSUE THREAD

**Issue by JohnVillalovos** [jdeluyck/kcoreorg-website#144]
Regarding your post: https://kcore.org/2023/03/27/ssh-unifi-fedora-37/

I am also using Fedora 37. My fix was the following.

```
Host edgeswitch
    PubkeyAcceptedAlgorithms ssh-rsa
    HostKeyAlgorithms ssh-rsa
    # The default got changed to 2048 and the EdgeSwitch uses 1024
    RequiredRSASize 1024
```

Might be helpful to you.

**Comment by jdeluyck** [comment]
Thank you! That part `RequiredRSASize 1024` was the section I was missing.

**Comment by JohnVillalovos** [comment]
Glad to help. It was a little bit of a journey trying to figure it out. Found your article along the way as a fellow Fedora and Ubiquiti user 🙂
